/*
 * $Id: postconfig.h,v 1.1 2006-04-07 03:06:19 kensaku Exp $
 */

#ifndef _CEAP_FIXCONFIG_H
#define _CEAP_FIXCONFIG_H

#define CEAP_PACKAGE PACKAGE
#undef PACKAGE
#define CEAP_PACKAGE_BUGREPORT PACKAGE_BUGREPORT
#undef PACKAGE_BUGREPORT
#define CEAP_PACKAGE_NAME PACKAGE_NAME
#undef PACKAGE_NAME
#define CEAP_PACKAGE_STRING PACKAGE_STRING
#undef PACKAGE_STRING
#define CEAP_PACKAGE_TARNAME PACKAGE_TARNAME
#undef PACKAGE_TARNAME
#define CEAP_PACKAGE_VERSION PACKAGE_VERSION
#undef PACKAGE_VERSION
#define CEAP_VERSION VERSION
#undef VERSION

/* restore original confdefs macroes */
#ifdef CEAP_ORIG_PACKAGE
#define PACKAGE CEAP_ORIG_PACKAGE
#undef CEAP_ORIG_PACKAGE
#endif
#ifdef CEAP_ORIG_PACKAGE_BUGREPORT
#define PACKAGE_BUGREPORT CEAP_ORIG_PACKAGE_BUGREPORT
#undef CEAP_ORIG_PACKAGE_BUGREPORT
#endif
#ifdef CEAP_ORIG_PACKAGE_NAME
#define PACKAGE_NAME CEAP_ORIG_PACKAGE_NAME
#undef CEAP_ORIG_PACKAGE_NAME
#endif
#ifdef CEAP_ORIG_PACKAGE_STRING
#define PACKAGE_STRING CEAP_ORIG_PACKAGE_STRING
#undef CEAP_ORIG_PACKAGE_STRING
#endif
#ifdef CEAP_ORIG_PACKAGE_TARNAME
#define PACKAGE_TARNAME CEAP_ORIG_PACKAGE_TARNAME
#undef CEAP_ORIG_PACKAGE_TARNAME
#endif
#ifdef CEAP_ORIG_PACKAGE_VERSION
#define PACKAGE_VERSION CEAP_ORIG_PACKAGE_VERSION
#undef CEAP_ORIG_PACKAGE_VERSION
#endif
#ifdef CEAP_ORIG_VERSION
#define VERSION CEAP_ORIG_VERSION
#undef CEAP_ORIG_VERSION
#endif

#endif /* !_CEAP_FIXCONFIG_H */
