/*
 * $Id: constants.h,v 1.4 2010-05-24 06:59:03 yatch Exp $
 */

#ifndef _CPANA_CONSTANTS_H
#define _CPANA_CONSTANTS_H

#define CPANA_PANA_UDP_PORT (716)
#define CPANA_PANA_MULTICAST_INADDR_STR "224.0.0.100"

#define CPANA_PANA_AUTH_KEY_CONSTANT_STR {'I', 'E', 'T', 'F', ' ', 'P', 'A', 'N', 'A'}

/* PANA Message Types */
#define CPANA_MSGTYPE_CLIENT_INITIATION	(1)
#define CPANA_MSGTYPE_AUTH		(2)
#define	CPANA_MSGTYPE_TERMINATION	(3)
#define	CPANA_MSGTYPE_NOTIFICATION	(4)
/* reserved for experimental messages 65520 - 65535 */

/* PANA Message Flags */
#define	CPANA_MSGFLAG_REQUEST	(0x8000)
#define	CPANA_MSGFLAG_START	(0x4000)
#define	CPANA_MSGFLAG_COMPLETE	(0x2000)
#define	CPANA_MSGFLAG_REAUTH	(0x1000)
#define	CPANA_MSGFLAG_PING	(0x0800)
#define	CPANA_MSGFLAG_IPUPDATE	(0x0400)

/* PANA AVP Flags */
#define CPANA_AVPFLAG_VENDOR (0x8000)
#define CPANA_AVPFLAG_MANDATORY (0x4000)

/* PANA AVP Codes */
#define CPANA_AVPCODE_AUTH	(1)
#define CPANA_AVPCODE_EAP_PAYLOAD	(2)
#define CPANA_AVPCODE_INTEGRITY_ALGORITHM (3)
#define CPANA_AVPCODE_KEY_ID	(4)
#define CPANA_AVPCODE_NONCE	(5)
#define CPANA_AVPCODE_PRF_ALGORITHM (6)
#define CPANA_AVPCODE_RESULT_CODE	(7)
#define CPANA_AVPCODE_SESSION_LIFETIME	(8)
#define CPANA_AVPCODE_TERMINATION_CAUSE	(9)

#define CPANA_AVPCODE_MAX  (9)

/* PANA AVP Algorithm AVP values */
/* prf */
#define CPANA_ALGORITHM_PRF_HMAC_SHA1		(2)
/* integrity */
#define CPANA_ALGORITHM_AUTH_HMAC_SHA1_160 	(7)

#endif /* !_CPANA_CONSTANTS_H */
