/*
 * $Id: postconfig.h,v 1.1 2006-04-07 03:06:19 kensaku Exp $
 */

#ifndef _CPANA_FIXCONFIG_H
#define _CPANA_FIXCONFIG_H

#define CPANA_PACKAGE PACKAGE
#undef PACKAGE
#define CPANA_PACKAGE_BUGREPORT PACKAGE_BUGREPORT
#undef PACKAGE_BUGREPORT
#define CPANA_PACKAGE_NAME PACKAGE_NAME
#undef PACKAGE_NAME
#define CPANA_PACKAGE_STRING PACKAGE_STRING
#undef PACKAGE_STRING
#define CPANA_PACKAGE_TARNAME PACKAGE_TARNAME
#undef PACKAGE_TARNAME
#define CPANA_PACKAGE_VERSION PACKAGE_VERSION
#undef PACKAGE_VERSION
#define CPANA_VERSION VERSION
#undef VERSION

/* restore original confdefs macroes */
#ifdef CPANA_ORIG_PACKAGE
#define PACKAGE CPANA_ORIG_PACKAGE
#undef CPANA_ORIG_PACKAGE
#endif
#ifdef CPANA_ORIG_PACKAGE_BUGREPORT
#define PACKAGE_BUGREPORT CPANA_ORIG_PACKAGE_BUGREPORT
#undef CPANA_ORIG_PACKAGE_BUGREPORT
#endif
#ifdef CPANA_ORIG_PACKAGE_NAME
#define PACKAGE_NAME CPANA_ORIG_PACKAGE_NAME
#undef CPANA_ORIG_PACKAGE_NAME
#endif
#ifdef CPANA_ORIG_PACKAGE_STRING
#define PACKAGE_STRING CPANA_ORIG_PACKAGE_STRING
#undef CPANA_ORIG_PACKAGE_STRING
#endif
#ifdef CPANA_ORIG_PACKAGE_TARNAME
#define PACKAGE_TARNAME CPANA_ORIG_PACKAGE_TARNAME
#undef CPANA_ORIG_PACKAGE_TARNAME
#endif
#ifdef CPANA_ORIG_PACKAGE_VERSION
#define PACKAGE_VERSION CPANA_ORIG_PACKAGE_VERSION
#undef CPANA_ORIG_PACKAGE_VERSION
#endif
#ifdef CPANA_ORIG_VERSION
#define VERSION CPANA_ORIG_VERSION
#undef CPANA_ORIG_VERSION
#endif

#endif /* !_CPANA_FIXCONFIG_H */
