/*
 * $Id: postconfig.h,v 1.1 2006-04-07 03:06:19 kensaku Exp $
 */

#ifndef _CLPE_POSTCONFIG_H
#define _CLPE_POSTCONFIG_H

#define CLPE_PACKAGE PACKAGE
#undef PACKAGE
#define CLPE_PACKAGE_BUGREPORT PACKAGE_BUGREPORT
#undef PACKAGE_BUGREPORT
#define CLPE_PACKAGE_NAME PACKAGE_NAME
#undef PACKAGE_NAME
#define CLPE_PACKAGE_STRING PACKAGE_STRING
#undef PACKAGE_STRING
#define CLPE_PACKAGE_TARNAME PACKAGE_TARNAME
#undef PACKAGE_TARNAME
#define CLPE_PACKAGE_VERSION PACKAGE_VERSION
#undef PACKAGE_VERSION
#define CLPE_VERSION VERSION
#undef VERSION

/* restore original confdefs macroes */
#ifdef CLPE_ORIG_PACKAGE
#define PACKAGE CLPE_ORIG_PACKAGE
#undef CLPE_ORIG_PACKAGE
#endif
#ifdef CLPE_ORIG_PACKAGE_BUGREPORT
#define PACKAGE_BUGREPORT CLPE_ORIG_PACKAGE_BUGREPORT
#undef CLPE_ORIG_PACKAGE_BUGREPORT
#endif
#ifdef CLPE_ORIG_PACKAGE_NAME
#define PACKAGE_NAME CLPE_ORIG_PACKAGE_NAME
#undef CLPE_ORIG_PACKAGE_NAME
#endif
#ifdef CLPE_ORIG_PACKAGE_STRING
#define PACKAGE_STRING CLPE_ORIG_PACKAGE_STRING
#undef CLPE_ORIG_PACKAGE_STRING
#endif
#ifdef CLPE_ORIG_PACKAGE_TARNAME
#define PACKAGE_TARNAME CLPE_ORIG_PACKAGE_TARNAME
#undef CLPE_ORIG_PACKAGE_TARNAME
#endif
#ifdef CLPE_ORIG_PACKAGE_VERSION
#define PACKAGE_VERSION CLPE_ORIG_PACKAGE_VERSION
#undef CLPE_ORIG_PACKAGE_VERSION
#endif
#ifdef CLPE_ORIG_VERSION
#define VERSION CLPE_ORIG_VERSION
#undef CLPE_ORIG_VERSION
#endif

#endif /* !_CLPE_POSTCONFIG_H */
